# frozen_string_literal: true
source "https://rubygems.org"
ruby "2.4.1"

gem "capybara"
gem "rspec"
gem 'capybara-screenshot'
gem 'selenium-webdriver'
gem 'webdrivers', git: 'https://github.com/shepmaster/webdrivers', branch: 'geckodriver-decompress'
